#!/bin/bash

usuario=$(whoami)

git clone https://aur.archlinux.org/yay.git
cd yay
runuser ${usuario} -c "makepkg -si"

sudo echo -e 'Section "InputClass"' > /etc/X11/xorg.conf.d/00-keyboard.conf
sudo echo -e 'Identifier "system-keyboard"' >> /etc/X11/xorg.conf.d/00-keyboard.conf
sudo echo -e 'MatchIsKeyboard "on"' >> /etc/X11/xorg.conf.d/00-keyboard.conf
sudo echo -e 'Option "XkbLayout" "latam"' >> /etc/X11/xorg.conf.d/00-keyboard.conf
sudo echo -e 'EndSection' >> /etc/X11/xorg.conf.d/00-keyboard.conf

